import { Experience } from "./experience.js";

export const amdiazExperiences: Array<Experience> = [
  {
    company: "DOMINGO ALONSO GROUP",
    position: "Desarrollador Full-Stack",
    startDate: "Julio 2021",
    endDate: "Actualidad",
    responsibilities: [
      "Desarrollo y mantenimiento de aplicaciones cloud con arquitectura de microservicios.",
      "Aseguramiento de la mantenibilidad y escalabilidad del código mediante el diseño guiado por pruebas, aplicación de las distintas prácticas DDD y principios de microdiseño SOLID.",
    ],
    technologies: [
      "C#",
      "TypeScript",
      ".NET CORE",
      "VUE",
      "REACT",
      "GIT",
      "SQL Server",
      "AZURE",
      "CQRS",
      "DDD",
      "TDD",
      "REST",
      "SCRUM",
      "XP",
    ],
  },
  {
    company: "Anexia",
    position: "Desarrollador Full-Stack",
    startDate: "Diciembre 2017",
    endDate: "Julio 2021",
    responsibilities: [
      "Desarrollo y soporte de múltiples aplicaciones web.",
      "Desarrollo de aplicaciones móviles nativas multiplataforma.",
      "Aseguramiento de la mantenibilidad y escalabilidad del software mediante la aplicación de principios SOLID, el uso de arquitecturas limpias (DDD, Hexagonal) y pruebas (TDD).",
    ],
    technologies: [
      "C#",
      "TypeScript",
      "Dart",
      "ASP.NET CORE",
      "Flutter",
      "Angular",
      "GIT",
      "TFS",
      "SQL Server",
      "Bloc",
      "CQRS",
      "DDD",
      "TDD",
      "REST",
    ],
  },
  {
    company: "VECTOR ITC-GROUP",
    position: "Analista Programador",
    startDate: "Mayo 2017",
    endDate: "Diciembre 2017",
    responsibilities: [
      "Análisis, diseño y desarrollo de soluciones web.",
      "Desarrollo de algoritmos de optimización de costes utilizando ANNs.",
      "Implantación de capas NoSQL y desarrollo e implantación de aplicaciones web y servicios web.",
    ],
    technologies: [
      "C#",
      "Angular",
      "ASP.NET CORE",
      "Python",
      "MongoDB",
      "GIT",
      "REST",
      "TDD",
      "DDD",
    ],
  },
  {
    company: "NOKIA",
    position: "Desarrollador de Aplicaciones Escritorio / Web",
    startDate: "Enero 2016",
    endDate: "Mayo 2017",
    responsibilities: [
      "Análisis, diseño y desarrollo de aplicaciones y aplicaciones web.",
      "Colaboración en proyectos de investigación, desarrollo e innovación (I+D+I).",
      "Diseño y desarrollo de un Sistema de Información Geográfica (GIS) FTTH, junto con módulos de automatización y reconstrucción de diseños.",
    ],
    technologies: ["VB", "C#", "WPF", "ASP.NET", "POSTGRESQL", "GIT", "CAD"],
  },
  {
    company: "Alcatel-Lucent",
    position: "Desarrollador de Aplicaciones Escritorio",
    startDate: "Septiembre 2014",
    endDate: "Enero 2016",
    responsibilities: [
      "Desarrollo de aplicaciones para análisis de datos",
      "Automatización de informes y KPIs",
      "Automatización de procesos utilizando VBA, .NET y MySQL.",
    ],
    technologies: ["VBA", ".NET", "MySQL"],
  },
  {
    company: "Freelance",
    position: "Diseñador y Desarrollador Web",
    startDate: "Noviembre 2013",
    endDate: "Octubre 2014",
    responsibilities: [
      "Diseño y desarrollo de varios proyectos web.",
      "Optimización de SEO y estrategias de marketing en redes sociales.",
      "Diseño de flyers, banners e imagen corporativa.",
    ],
    technologies: ["HTML5", "CSS3", "GRUNT", "JQUERY", "LESS"],
  },
  {
    company: "LA SALLE",
    position: "Técnico de Sistemas",
    startDate: "Octubre 2013",
    endDate: "Febrero 2014",
    responsibilities: [
      "Mantenimiento e instalación de sistemas basados en Windows Server (prácticas).",
    ],
    technologies: ["Windows Server"],
  },
  {
    company: "Freelance",
    position: "Desarrollador Web",
    startDate: "Junio 2013",
    endDate: "Octubre 2013",
    responsibilities: [
      "Desarrollo front-end responsive utilizando HTML5 y CSS3.",
      "Uso del framework GRUNT y las librerías JQUERY y LESS.",
      "Proyecto destacado: desarrollo del portal www.RACE.es.",
    ],
    technologies: ["HTML5", "CSS3", "GRUNT", "JQUERY", "LESS"],
  },
  {
    company: "Signlab",
    position: "Desarrollador de Aplicaciones Web",
    startDate: "Enero 2013",
    endDate: "Abril 2013",
    responsibilities: [
      "Colaboración en el desarrollo de una aplicación móvil utilizando JAVA, PHP, XML y MySQL.",
    ],
    technologies: ["JAVA", "PHP", "XML", "MySQL"],
  },
  {
    company: "XUL COMUNICATION SOCIAL",
    position: "Desarrollador de Aplicaciones Web",
    startDate: "Octubre 2012",
    endDate: "Diciembre 2012",
    responsibilities: [
      "Colaboración en el desarrollo de una aplicación móvil utilizando JAVA, PHP, XML y MySQL (prácticas)",
    ],
    technologies: ["JAVA", "PHP", "XML", "MySQL"],
  },
];
